sudo: required
dist: focal
language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config libglib2.0-dev fcitx-libs-dev
script:
  - ./autogen.sh && ./configure --prefix=/tmp/local && make && make install
